export const img = (file: string) => `/images/${file}`;

export const images = {
  logo: img("4V0XvuRqNZgZlZ6hbED1Lm2yt9I.png"),
  logoFooter: img("EAXMpVOGAzqBvjaoLmAgV2N1E.png"),
  favicon: img("XDhymzkEA6AaDsbEusR7acKypTQ.svg"),
  appleIcon: img("X5hDat06E74iJTnTptDu3q5suYg.png"),
  og: img("88MPTeWoZPXJQAtG5sf59gE45JE.png"),

  heroBurgerSplash: img("kZ1AHLZFQ9NSUnVYH0vsag03Cvk.png"),
  heroBurgerAlt: img("zOewDJhXAeRdBt4kpWy6aStvzg.png"),
  heroChilis: img("efZbiaxkt4S7qZOEiT35wKtzlA.png"),
  heroTomatoes: img("MI9CJPJjOLwLa8oeaVKPWbwChzM.png"),
  heroBowl: img("hXqR9wP2PmGMjgu4zIGdxkTbiRw.png"),
  heroPizza: img("oLgh5qLEZk1Z56ZHctTJR2hEFkI.png"),

  catBurger: img("kvPVAAWFeVR4t13Jrj2VdVIIu8w.png"),
  catPizza: img("rwuiZgFnQOwvF0OJSq0FrL7lX8.png"),
  catChicken: img("olua11LiLGixBmZar3RLrl6Of0.png"),
  catFries: img("egmqsnkCPbkqWBi6grH37s18ULA.png"),
  catSandwich: img("mT85liBc3WncZAZjOYPm0hxwqw.png"),
  catPasta: img("R3hDGTxsRwb7RxBngwboES0Mm10.png"),
  catSalad: img("rajT3ykS2nZOMcmFbyOUMvQDnY.png"),

  offerChef: img("PDrjHbZPzqvaYnSBHOi3BevkHEA.png"),
  offerOven: img("G9pCFoPAGXfnPwcyrzkEgyB4F8.png"),
  offerBurger: img("yBpDxeFHBzSGgy8HDjSPCQLxo.png"),

  menuSignature: img("LSG8mgoQxRghiP10xoZP88BBmec.png"),
  menuPasta: img("t7O6pbw05MR4c8nExI16tMxQxs.png"),
  menuSteak: img("Eb7M05XvDgIq6BvR0VVIk7fm8c.png"),
  menuBurgerBoard: img("WaUcPXj1Lw9rC3n3HkJdwyGF8U.png"),
  menuTall: img("MzwaY3mYVxJm5xCnwxTJZ6hGiX8.png"),

  iconFood: img("t6Vc8Uf3xdcgamma35bup6Posk.png"),
  iconAmbience: img("rwUFDwCrMcIRGeKwZUgXQAT6rjM.png"),
  iconService: img("hQFDHwF7zFZ7JlpTobXqYhj55Dg.png"),
  iconFresh: img("Vgx372HTrjvNBEzuhNnem5XzVY.png"),

  cateringRisotto: img("MTMqdglCS4lnccrM6MYyMHoonOw.png"),
  cateringPlatter: img("PdOkbbnJb9s1oLRaHZs17983bs.png"),
  cateringSandwich: img("Q7SrMMajZKsExYsR1AGymr6olwU.png"),

  quote: img("JKxdyAqYY4I9jDd959ZmvZUAOX8.png"),
  testimonial1: img("qEq4OOzgjjfINR2LMhbSG60PVs.png"),
  testimonial2: img("g70d44oB1EZTQu5yrXJS82KQ5bU.png"),
  testimonial3: img("GXekj0nub3e6eQ5Xb4mKxEYdvk.png"),
  testimonial4: img("m4adLnumDxTnaHZbopp6fqixYg.png"),
  testimonialDecor1: img("DTyEWjgxXVHiprhDicjOkSY6r0.png"),
  testimonialDecor2: img("mFLw1mionxQN9EW131GWS2Xf8.png"),
  testimonialDecor3: img("uZMAxPZBjYD24RPz01MHKlQcgQ.png"),

  gallery1: img("Dysv83hSR9nnEHr6aWRexPubX74.png"),
  gallery2: img("pZQYV6u2cKzqxQTKuJp3yzETCY.png"),
  gallery3: img("SXpxP4p7RRgl4JfVSbOBbMrCc.png"),

  blogBurger: img("GFKcZBjOIWmkTPX6PGWoAkB06o.png"),
  blogFresh: img("poWpuvm8Y7LquNolHShRIkBnKAk.png"),
  blogChicken: img("JzXalahHuUh5P17Hvh92YtKXrPw.png"),
  blogPasta: img("yt66gj5vWeZVujdBkvD4Ty5u0.png"),
  blogNachos: img("WdYDoXsCRF182zo0nlTq93LyZ94.png"),
  blogOnion: img("n2bjxGaQ2NJtR3Gj9yY0pjd0o.png"),

  ctaFood: img("MYzH9eyGRtT91VQNZEz9lrtUAUA.png"),
  ctaFood2: img("lLgVuH0b05INFT57guXDCC0Jw.png"),

  arrow: img("BAruMtP09ylMxhxVyDeiWUp9Jks.svg"),
  decoLeaf: img("6dqy5LkEKH2ubWVihNvsUo6pZJ0.png"),
  decoLeaf2: img("3opAQeDEqKqptq03v7eAfIGhRc.png"),
  decoCircle: img("3Pzdh2wAuyNnoARYxr1z1XxY.png"),
  decoBadge: img("yiKoj1dHI5eWJkn415Gt5eCcc.png"),
  decoBadge2: img("7AilhkeRKXGe30uL97uTydB4sHg.png"),

  about1: img("65ZGFUlSRLqb6eeHaxmW5fxyvWk.png"),
  about2: img("6D7zmtTd4AHxZM1n4eo8EJrK6g.png"),
  about3: img("7eAUx8kImfdcQpJqaksx6qQVjQ.png"),
  aboutHero: img("7GDW1CAgGBe6PE4M0SHwZzm085I.png"),
  event1: img("8tMesCqfxibAU0g4xn1Jtzp67fU.png"),
  event2: img("AfWmhe5Si1qX9RYIAuuxyHrdtng.png"),
  event3: img("BjQ35XHUZ3SuDS5VRdh0Dike9eo.png"),
  event4: img("Gh2gXbOR2Pvjew720RvD22MiNs.png"),
  wings: img("HcdoOTSZPp3kFCnrIHCaHJKTdUo.png"),
  dish1: img("ICyn0FPUmpNqP38T2ia4eQwUo.png"),
  dish2: img("ip6hODQlZ4bcT0m5xtEix4CaZ0c.png"),
  dish3: img("jLzwVdVTfCYGhAkibhFFjTUYK5Q.png"),
  dish4: img("kXOJ3Fxb7dGBgj7T6WW2Uk4PaY.png"),
  dish5: img("mj9oqRFzQQHMxHfuJGwvP7RVqs.png"),
  dish6: img("NCWICeXYtqPRSXmWJNA8wwxvyTc.png"),
  dish7: img("NHQ5ZzlijebHkXFfxy5LOFx83Gs.png"),
  dish8: img("PLXvjMmngrz0fgkQnl4tbWtlWtE.png"),
  dish9: img("PmQVJbMvQ8GtFyaC3n7xN53ZQ.png"),
  dish10: img("RvErjLzvutZQvmxKLQRzIUShRs.png"),
  dish11: img("vMlRBvVBiaQP9bCGW3buSkae80Y.png"),
  dish12: img("VY6Uau6ieVPpq9Qp2rvLMUaOo.png"),
  dish13: img("wChvTwcwhi1FeaZRWz4TbSBQYXo.png"),
  dish14: img("x1VCnHkFbz5Kldkca9QS5GmvHA.png"),
  dish15: img("xRP0oIAwmCNvXrW406NjtJkZk.png"),
  dish16: img("YS9LRJXwyDIUYf5hPzuiiZXXqIU.png"),
  dish17: img("dZVXVXh1CfukyFMs1CWSSHW8RQ.png"),
  dish18: img("geEkFrxRCXme0xk2fVivVmvVLA.png"),
  contactArt: img("7nv5vQHZkqrq2M6lOicVkvy692Q.png"),
  smallIcon1: img("2JfKHabipTPU2CIGv3YaX0fug.png"),
  smallIcon2: img("7vZWZAEixuocByUxRoq7wJUzgG0.png"),
  smallIcon3: img("bjVo0RR01HqcLUOo3OaCT2SJU.png"),
  smallIcon4: img("D1nlLCDD3pQ23pTdOO68vg1Z2aQ.png"),
  smallIcon5: img("PEIaKZmokBZL3azMPlOEfpvyrA.png"),
  smallIcon6: img("SrOPdSnp63uTPEeW9kKGOrQxU.png"),
  chevron: img("QmoKQcOr0nr3XAFcXOM7yBYwU.svg"),
};
